### ISSUE TITLE
How do you handle 2x certain resource?

### ISSUE THREAD

**Issue by dsfrederic** [Azure/terraform-azurerm-naming#59]
How do you handle 2x certain resource? Do you create this module 2 times? For ex. 2 resource groups

**Comment by srvrguy** [comment]
Since nobody else has offered anything, I'll try to provide some advice.

There are a few ways you can handle this, depending on your needs.

1. You can import the module multiple times with a different name. The downside is that you will have two "resources" for each module import as the random string and random letter that are generated on first use are stored. This method is pretty quick, but doesn't scale well and can add a bunch of unneeded resources to your environment.
2. You can use the "name" property of the module and add your own unique ending to the resource name. You may need to check that you are not exceeding the maximum length or using dashes where not supported for the resource type. There are properties you can use to implement checks for that.
3. You can follow the "Advanced Usage" section of the readme and implement your own "name" system using the properties of the module so that you can make a unique name. Using this method is more work as you need to check for max length and other things, but you get the benefit of having all the properties that give you the constraints. This method is more complex, but can scale very well while still maintaining a consistent naming scheme.

**Comment by dsfrederic** [comment]
Okay what I did for now is append a number 01 to the name. If i require a 2nd resource I'll replace the 01 with 02 and so on.
